package com.cdb96.ncmconverter4a

import com.cdb96.ncmconverter4a.converter.kgg.KggBatchKeys
import com.cdb96.ncmconverter4a.converter.kgg.KggDbDecryptor
import com.cdb96.ncmconverter4a.converter.kgg.KggKeyDatabase
import com.cdb96.ncmconverter4a.converter.kgg.MMKVParser
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.runBlocking
import java.io.ByteArrayOutputStream
import java.io.File
import java.nio.file.Files
import java.util.concurrent.CountDownLatch
import java.util.concurrent.Executors
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicInteger
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNull
import kotlin.test.assertSame

class KggDatabaseCacheTest {
    private val ekey = "AQIDBAUGBwijvfhds1lCBVcHv7WluvwG".encodeToByteArray()
    private val key = ByteArray(14) { (it + 1).toByte() }

    @Test
    fun concurrentFilesShareOneLazySnapshotAndIndependentLookups() {
        val loads = AtomicInteger()
        val bytes = mmkv((0 until 64).map { "hash-$it" to ekey })
        val keys = KggBatchKeys {
            loads.incrementAndGet()
            val parser = MMKVParser(bytes)
            KggKeyDatabase(parser::getBytes)
        }
        assertEquals(0, loads.get())
        val pool = Executors.newFixedThreadPool(8)
        val start = CountDownLatch(1)
        try {
            val results = (0 until 64).map { index ->
                pool.submit<ByteArray> {
                    start.await()
                    keys.getKey("hash-$index")
                }
            }
            start.countDown()
            results.forEach { assertContentEquals(key, it.get(10, TimeUnit.SECONDS)) }
            assertEquals(1, loads.get())
            assertFailsWith<IllegalStateException> { keys.getKey("missing") }
            assertContentEquals(key, keys.getKey("hash-0"))
        } finally {
            pool.shutdownNow()
        }
    }

    @Test
    fun failedLoadIsSharedButCancellationIsNotCached() {
        val loads = AtomicInteger()
        val failure = IllegalStateException("database unavailable")
        val failed = KggBatchKeys {
            loads.incrementAndGet()
            throw failure
        }
        repeat(4) {
            assertSame(failure, assertFailsWith<IllegalStateException> { failed.getKey("hash-$it") })
        }
        assertEquals(1, loads.get())

        val attempts = AtomicInteger()
        val cancelled = KggBatchKeys {
            if (attempts.incrementAndGet() == 1) throw CancellationException()
            KggKeyDatabase { ekey }
        }
        assertFailsWith<CancellationException> { cancelled.getKey("hash") }
        assertContentEquals(key, cancelled.getKey("hash"))
        assertEquals(2, attempts.get())
    }

    @Test
    fun mmkvIndexPreservesDuplicatesValidPrefixAndByteExactKeys() {
        val encoded = mmkv(listOf(
            "same" to byteArrayOf(1), "中文" to ByteArray(300) { 2 },
            "same" to byteArrayOf(9), "empty" to ByteArray(0),
        ))
        val malformedKey = byteArrayOf(1, 0xFF.toByte(), 0x0A, 0, 1, 7)
        val replacement = mmkv(listOf("\uFFFD" to byteArrayOf(8)))
        val validReplacement = replacement.copyOfRange(8, replacement.size)
        val parser = MMKVParser(encoded + malformedKey + validReplacement + byteArrayOf(10, 1))
        assertContentEquals(byteArrayOf(1), parser.getBytes("same"))
        assertContentEquals(ByteArray(300) { 2 }, parser.getBytes("中文"))
        assertContentEquals(ByteArray(0), parser.getBytes("empty"))
        assertContentEquals(byteArrayOf(8), parser.getBytes("\uFFFD"))
        assertNull(parser.getBytes("missing"))
        parser.getBytes("same")!![0] = 99
        assertContentEquals(byteArrayOf(1), parser.getBytes("same"))
    }

    @Test
    fun sqliteProjectionAndFallbackKeepOverflowKeysFromReorderedColumns() {
        // Generated by Python's SQLite engine: 1 KiB pages, interior B-tree,
        // reordered key columns, unrelated numeric/BLOB columns and overflow.
        val plain = javaClass.getResourceAsStream("/kgg/keys.sqlite")!!.use { it.readBytes() }
        val expected = (1..20).associate { index -> hash(index) to ('A' + index - 1).toString().repeat(1024) }
            .toMutableMap().apply {
                this[hash(1)] = "Z".repeat(1024) // last SQLite row wins, as before
                this[hash(21)] = "" // an empty key is distinct from NULL
            }
        val root = Files.createTempDirectory("kgg-sqlite-cache").toFile()
        try {
            for ((name, bytes) in listOf("plain.db" to plain, "encrypted.db" to ReferenceKggDb.encryptDatabase(plain))) {
                val file = File(root, name).apply { writeBytes(bytes) }
                val database = loadDesktopKggDatabase(file.path)
                file.writeBytes(byteArrayOf(0))
                assertEquals(expected, KggDbDecryptor.extractKeyMapping(plain))
                expected.forEach { (hash, value) -> assertContentEquals(value.encodeToByteArray(), database.getBytes(hash)) }
                val legacy = hash(99)
                assertContentEquals("L".repeat(1024).encodeToByteArray(), database.getBytes(legacy))
                database.getBytes(legacy)!![0] = 0
                assertContentEquals("L".repeat(1024).encodeToByteArray(), database.getBytes(legacy))
                repeat(2) { assertNull(database.getBytes(hash(100))) }
            }
        } finally {
            root.deleteRecursively()
        }
    }

    @Test
    fun conversionUsesBatchSnapshotAndReloadsChangedDatabaseNextBatch() = runBlocking {
        val root = Files.createTempDirectory("kgg-batch-snapshot").toFile()
        try {
            val audio = "ID3".encodeToByteArray() + ByteArray(4096) { it.toByte() }
            val files = (1..3).map { index -> File(root, "song-$index.kgg").apply { writeBytes(kgg(hash(index), audio)) } }
            val database = File(root, "keys.mmkv").apply { writeBytes(mmkv((1..3).map { hash(it) to ekey })) }
            val output = File(root, "output")
            val facade = DesktopConversionFacade(output)
            val first = facade.processFiles(files.map { it.path }, 1, true, true, database.path) { processed, _, _ ->
                if (processed == 1) database.writeBytes(byteArrayOf(0))
            }
            assertEquals(3, first.successCount, first.failedFiles.toString())
            files.forEach { assertContentEquals(audio, File(output, "${it.nameWithoutExtension}.mp3").readBytes()) }
            val second = facade.processFiles(files.map { it.path }, 3, true, true, database.path) { _, _, _ -> }
            assertEquals(3, second.failureCount)
            database.writeBytes(mmkv((1..3).map { hash(it) to ekey }))
            val third = facade.processFiles(files.map { it.path }, 3, true, true, database.path) { _, _, _ -> }
            assertEquals(3, third.successCount, third.failedFiles.toString())
        } finally {
            root.deleteRecursively()
        }
    }

    private fun hash(index: Int): String = index.toString(16).padStart(32, '0')

    private fun mmkv(entries: List<Pair<String, ByteArray>>): ByteArray = ByteArrayOutputStream().apply {
        write(ByteArray(8))
        for ((name, value) in entries) {
            val key = name.encodeToByteArray()
            write(key.size)
            write(key)
            write(byteArrayOf(0x0A, 0))
            var length = value.size
            while (length >= 128) {
                write((length and 127) or 128)
                length = length ushr 7
            }
            write(length)
            write(value)
        }
    }.toByteArray()

    private fun kgg(hash: String, audio: ByteArray): ByteArray {
        val header = byteArrayOf(
            0x7C, 0xD5.toByte(), 0x32, 0xEB.toByte(), 0x86.toByte(), 0x02, 0x7F, 0x4B,
            0xA8.toByte(), 0xAF.toByte(), 0xA6.toByte(), 0x8E.toByte(), 0x0F, 0xFF.toByte(), 0x99.toByte(), 0x14,
        ).copyOf(1024).apply {
            this[17] = 4 // audio offset = 1024, little endian
            this[20] = 5
            this[68] = hash.length.toByte()
            hash.encodeToByteArray().copyInto(this, 72)
        }
        return header + audio.copyOf().also { ReferenceQmcMap(key).decrypt(it, 0) }
    }
}
